//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ground_Service_Control.GMC {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MapObject", Namespace="DKO-Airport-Ground-Movement-Control")]
    [System.SerializableAttribute()]
    public partial class MapObject : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private Ground_Service_Control.GMC.MapObjectType MapObjectTypeField;
        
        private int NumberField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public Ground_Service_Control.GMC.MapObjectType MapObjectType {
            get {
                return this.MapObjectTypeField;
            }
            set {
                if ((this.MapObjectTypeField.Equals(value) != true)) {
                    this.MapObjectTypeField = value;
                    this.RaisePropertyChanged("MapObjectType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Number {
            get {
                return this.NumberField;
            }
            set {
                if ((this.NumberField.Equals(value) != true)) {
                    this.NumberField = value;
                    this.RaisePropertyChanged("Number");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MapObjectType", Namespace="DKO-Airport-Ground-Movement-Control")]
    public enum MapObjectType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Runway = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Garage = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ServiceArea = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Airport = 3,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CoordinateTuple", Namespace="DKO-Airport-Ground-Movement-Control")]
    [System.SerializableAttribute()]
    public partial class CoordinateTuple : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int XField;
        
        private int YField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int X {
            get {
                return this.XField;
            }
            set {
                if ((this.XField.Equals(value) != true)) {
                    this.XField = value;
                    this.RaisePropertyChanged("X");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Y {
            get {
                return this.YField;
            }
            set {
                if ((this.YField.Equals(value) != true)) {
                    this.YField = value;
                    this.RaisePropertyChanged("Y");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MoveObjectType", Namespace="DKO-Airport-Ground-Movement-Control")]
    public enum MoveObjectType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        None = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Plane = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FollowMeVan = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ContainerLoader = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BaggageTractor = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CateringTruck = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Deicer = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PassengerStairs = 7,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PassengerBus = 8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        VipShuttle = 9,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SnowRemovalVehicle = 10,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="DKO-Airport-Ground-Movement-Control", ConfigurationName="GMC.GMCSoap")]
    public interface GMCSoap {
        
        // CODEGEN: Generating message contract since element name from from namespace DKO-Airport-Ground-Movement-Control is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="DKO-Airport-Ground-Movement-Control/GetRoute", ReplyAction="*")]
        Ground_Service_Control.GMC.GetRouteResponse GetRoute(Ground_Service_Control.GMC.GetRouteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="DKO-Airport-Ground-Movement-Control/GetRoute", ReplyAction="*")]
        System.Threading.Tasks.Task<Ground_Service_Control.GMC.GetRouteResponse> GetRouteAsync(Ground_Service_Control.GMC.GetRouteRequest request);
        
        // CODEGEN: Generating message contract since element name coordinate from namespace DKO-Airport-Ground-Movement-Control is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="DKO-Airport-Ground-Movement-Control/Step", ReplyAction="*")]
        Ground_Service_Control.GMC.StepResponse Step(Ground_Service_Control.GMC.StepRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="DKO-Airport-Ground-Movement-Control/Step", ReplyAction="*")]
        System.Threading.Tasks.Task<Ground_Service_Control.GMC.StepResponse> StepAsync(Ground_Service_Control.GMC.StepRequest request);
        
        // CODEGEN: Generating message contract since element name CheckRunwayAwailabilityResult from namespace DKO-Airport-Ground-Movement-Control is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="DKO-Airport-Ground-Movement-Control/CheckRunwayAwailability", ReplyAction="*")]
        Ground_Service_Control.GMC.CheckRunwayAwailabilityResponse CheckRunwayAwailability(Ground_Service_Control.GMC.CheckRunwayAwailabilityRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="DKO-Airport-Ground-Movement-Control/CheckRunwayAwailability", ReplyAction="*")]
        System.Threading.Tasks.Task<Ground_Service_Control.GMC.CheckRunwayAwailabilityResponse> CheckRunwayAwailabilityAsync(Ground_Service_Control.GMC.CheckRunwayAwailabilityRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetRouteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetRoute", Namespace="DKO-Airport-Ground-Movement-Control", Order=0)]
        public Ground_Service_Control.GMC.GetRouteRequestBody Body;
        
        public GetRouteRequest() {
        }
        
        public GetRouteRequest(Ground_Service_Control.GMC.GetRouteRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="DKO-Airport-Ground-Movement-Control")]
    public partial class GetRouteRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Ground_Service_Control.GMC.MapObject from;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public Ground_Service_Control.GMC.MapObject to;
        
        public GetRouteRequestBody() {
        }
        
        public GetRouteRequestBody(Ground_Service_Control.GMC.MapObject from, Ground_Service_Control.GMC.MapObject to) {
            this.from = from;
            this.to = to;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetRouteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetRouteResponse", Namespace="DKO-Airport-Ground-Movement-Control", Order=0)]
        public Ground_Service_Control.GMC.GetRouteResponseBody Body;
        
        public GetRouteResponse() {
        }
        
        public GetRouteResponse(Ground_Service_Control.GMC.GetRouteResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="DKO-Airport-Ground-Movement-Control")]
    public partial class GetRouteResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Ground_Service_Control.GMC.CoordinateTuple[] GetRouteResult;
        
        public GetRouteResponseBody() {
        }
        
        public GetRouteResponseBody(Ground_Service_Control.GMC.CoordinateTuple[] GetRouteResult) {
            this.GetRouteResult = GetRouteResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class StepRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Step", Namespace="DKO-Airport-Ground-Movement-Control", Order=0)]
        public Ground_Service_Control.GMC.StepRequestBody Body;
        
        public StepRequest() {
        }
        
        public StepRequest(Ground_Service_Control.GMC.StepRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="DKO-Airport-Ground-Movement-Control")]
    public partial class StepRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Ground_Service_Control.GMC.CoordinateTuple coordinate;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public Ground_Service_Control.GMC.MoveObjectType type;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public System.Guid id;
        
        public StepRequestBody() {
        }
        
        public StepRequestBody(Ground_Service_Control.GMC.CoordinateTuple coordinate, Ground_Service_Control.GMC.MoveObjectType type, System.Guid id) {
            this.coordinate = coordinate;
            this.type = type;
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class StepResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="StepResponse", Namespace="DKO-Airport-Ground-Movement-Control", Order=0)]
        public Ground_Service_Control.GMC.StepResponseBody Body;
        
        public StepResponse() {
        }
        
        public StepResponse(Ground_Service_Control.GMC.StepResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="DKO-Airport-Ground-Movement-Control")]
    public partial class StepResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool StepResult;
        
        public StepResponseBody() {
        }
        
        public StepResponseBody(bool StepResult) {
            this.StepResult = StepResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CheckRunwayAwailabilityRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CheckRunwayAwailability", Namespace="DKO-Airport-Ground-Movement-Control", Order=0)]
        public Ground_Service_Control.GMC.CheckRunwayAwailabilityRequestBody Body;
        
        public CheckRunwayAwailabilityRequest() {
        }
        
        public CheckRunwayAwailabilityRequest(Ground_Service_Control.GMC.CheckRunwayAwailabilityRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="DKO-Airport-Ground-Movement-Control")]
    public partial class CheckRunwayAwailabilityRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public System.Guid planeGuid;
        
        public CheckRunwayAwailabilityRequestBody() {
        }
        
        public CheckRunwayAwailabilityRequestBody(System.Guid planeGuid) {
            this.planeGuid = planeGuid;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CheckRunwayAwailabilityResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CheckRunwayAwailabilityResponse", Namespace="DKO-Airport-Ground-Movement-Control", Order=0)]
        public Ground_Service_Control.GMC.CheckRunwayAwailabilityResponseBody Body;
        
        public CheckRunwayAwailabilityResponse() {
        }
        
        public CheckRunwayAwailabilityResponse(Ground_Service_Control.GMC.CheckRunwayAwailabilityResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="DKO-Airport-Ground-Movement-Control")]
    public partial class CheckRunwayAwailabilityResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Ground_Service_Control.GMC.MapObject CheckRunwayAwailabilityResult;
        
        public CheckRunwayAwailabilityResponseBody() {
        }
        
        public CheckRunwayAwailabilityResponseBody(Ground_Service_Control.GMC.MapObject CheckRunwayAwailabilityResult) {
            this.CheckRunwayAwailabilityResult = CheckRunwayAwailabilityResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface GMCSoapChannel : Ground_Service_Control.GMC.GMCSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GMCSoapClient : System.ServiceModel.ClientBase<Ground_Service_Control.GMC.GMCSoap>, Ground_Service_Control.GMC.GMCSoap {
        
        public GMCSoapClient() {
        }
        
        public GMCSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GMCSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GMCSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GMCSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Ground_Service_Control.GMC.GetRouteResponse Ground_Service_Control.GMC.GMCSoap.GetRoute(Ground_Service_Control.GMC.GetRouteRequest request) {
            return base.Channel.GetRoute(request);
        }
        
        public Ground_Service_Control.GMC.CoordinateTuple[] GetRoute(Ground_Service_Control.GMC.MapObject from, Ground_Service_Control.GMC.MapObject to) {
            Ground_Service_Control.GMC.GetRouteRequest inValue = new Ground_Service_Control.GMC.GetRouteRequest();
            inValue.Body = new Ground_Service_Control.GMC.GetRouteRequestBody();
            inValue.Body.from = from;
            inValue.Body.to = to;
            Ground_Service_Control.GMC.GetRouteResponse retVal = ((Ground_Service_Control.GMC.GMCSoap)(this)).GetRoute(inValue);
            return retVal.Body.GetRouteResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Ground_Service_Control.GMC.GetRouteResponse> Ground_Service_Control.GMC.GMCSoap.GetRouteAsync(Ground_Service_Control.GMC.GetRouteRequest request) {
            return base.Channel.GetRouteAsync(request);
        }
        
        public System.Threading.Tasks.Task<Ground_Service_Control.GMC.GetRouteResponse> GetRouteAsync(Ground_Service_Control.GMC.MapObject from, Ground_Service_Control.GMC.MapObject to) {
            Ground_Service_Control.GMC.GetRouteRequest inValue = new Ground_Service_Control.GMC.GetRouteRequest();
            inValue.Body = new Ground_Service_Control.GMC.GetRouteRequestBody();
            inValue.Body.from = from;
            inValue.Body.to = to;
            return ((Ground_Service_Control.GMC.GMCSoap)(this)).GetRouteAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Ground_Service_Control.GMC.StepResponse Ground_Service_Control.GMC.GMCSoap.Step(Ground_Service_Control.GMC.StepRequest request) {
            return base.Channel.Step(request);
        }
        
        public bool Step(Ground_Service_Control.GMC.CoordinateTuple coordinate, Ground_Service_Control.GMC.MoveObjectType type, System.Guid id) {
            Ground_Service_Control.GMC.StepRequest inValue = new Ground_Service_Control.GMC.StepRequest();
            inValue.Body = new Ground_Service_Control.GMC.StepRequestBody();
            inValue.Body.coordinate = coordinate;
            inValue.Body.type = type;
            inValue.Body.id = id;
            Ground_Service_Control.GMC.StepResponse retVal = ((Ground_Service_Control.GMC.GMCSoap)(this)).Step(inValue);
            return retVal.Body.StepResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Ground_Service_Control.GMC.StepResponse> Ground_Service_Control.GMC.GMCSoap.StepAsync(Ground_Service_Control.GMC.StepRequest request) {
            return base.Channel.StepAsync(request);
        }
        
        public System.Threading.Tasks.Task<Ground_Service_Control.GMC.StepResponse> StepAsync(Ground_Service_Control.GMC.CoordinateTuple coordinate, Ground_Service_Control.GMC.MoveObjectType type, System.Guid id) {
            Ground_Service_Control.GMC.StepRequest inValue = new Ground_Service_Control.GMC.StepRequest();
            inValue.Body = new Ground_Service_Control.GMC.StepRequestBody();
            inValue.Body.coordinate = coordinate;
            inValue.Body.type = type;
            inValue.Body.id = id;
            return ((Ground_Service_Control.GMC.GMCSoap)(this)).StepAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Ground_Service_Control.GMC.CheckRunwayAwailabilityResponse Ground_Service_Control.GMC.GMCSoap.CheckRunwayAwailability(Ground_Service_Control.GMC.CheckRunwayAwailabilityRequest request) {
            return base.Channel.CheckRunwayAwailability(request);
        }
        
        public Ground_Service_Control.GMC.MapObject CheckRunwayAwailability(System.Guid planeGuid) {
            Ground_Service_Control.GMC.CheckRunwayAwailabilityRequest inValue = new Ground_Service_Control.GMC.CheckRunwayAwailabilityRequest();
            inValue.Body = new Ground_Service_Control.GMC.CheckRunwayAwailabilityRequestBody();
            inValue.Body.planeGuid = planeGuid;
            Ground_Service_Control.GMC.CheckRunwayAwailabilityResponse retVal = ((Ground_Service_Control.GMC.GMCSoap)(this)).CheckRunwayAwailability(inValue);
            return retVal.Body.CheckRunwayAwailabilityResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Ground_Service_Control.GMC.CheckRunwayAwailabilityResponse> Ground_Service_Control.GMC.GMCSoap.CheckRunwayAwailabilityAsync(Ground_Service_Control.GMC.CheckRunwayAwailabilityRequest request) {
            return base.Channel.CheckRunwayAwailabilityAsync(request);
        }
        
        public System.Threading.Tasks.Task<Ground_Service_Control.GMC.CheckRunwayAwailabilityResponse> CheckRunwayAwailabilityAsync(System.Guid planeGuid) {
            Ground_Service_Control.GMC.CheckRunwayAwailabilityRequest inValue = new Ground_Service_Control.GMC.CheckRunwayAwailabilityRequest();
            inValue.Body = new Ground_Service_Control.GMC.CheckRunwayAwailabilityRequestBody();
            inValue.Body.planeGuid = planeGuid;
            return ((Ground_Service_Control.GMC.GMCSoap)(this)).CheckRunwayAwailabilityAsync(inValue);
        }
    }
}
