//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ground_Service_Control.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://airport-dko-gmc.azurewebsites.net/gmc.asmx")]
        public string Ground_Service_Control_GMC_GMC {
            get {
                return ((string)(this["Ground_Service_Control_GMC_GMC"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://airport-dko-aircraft-generator.azurewebsites.net/AircraftGenerator.asmx")]
        public string Ground_Service_Control_AircraftGenerator_AircraftGenerator {
            get {
                return ((string)(this["Ground_Service_Control_AircraftGenerator_AircraftGenerator"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://airport-dko-services.azurewebsites.net/CateringTruck.asmx")]
        public string Ground_Service_Control_CateringTruck_CateringTruck {
            get {
                return ((string)(this["Ground_Service_Control_CateringTruck_CateringTruck"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://airport-dko-services.azurewebsites.net/ContainerLoader.asmx")]
        public string Ground_Service_Control_ContainerLoader_ContainerLoader {
            get {
                return ((string)(this["Ground_Service_Control_ContainerLoader_ContainerLoader"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://airport-dko-services.azurewebsites.net/PassengerBus.asmx")]
        public string Ground_Service_Control_PassengerBus_PassengerBus {
            get {
                return ((string)(this["Ground_Service_Control_PassengerBus_PassengerBus"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://airport-dko-services.azurewebsites.net/PassengerStairs.asmx")]
        public string Ground_Service_Control_PassengerStairs_PassengerStairs {
            get {
                return ((string)(this["Ground_Service_Control_PassengerStairs_PassengerStairs"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://airport-dko-services.azurewebsites.net/Refueler.asmx")]
        public string Ground_Service_Control_Refueler_Refueler {
            get {
                return ((string)(this["Ground_Service_Control_Refueler_Refueler"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://airport-dko-services.azurewebsites.net/VIPShuttle.asmx")]
        public string Ground_Service_Control_VIPShuttle_VIPShuttle {
            get {
                return ((string)(this["Ground_Service_Control_VIPShuttle_VIPShuttle"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://airport-dko-passengers.azurewebsites.net/WebServiceInformationPanel.asmx")]
        public string Ground_Service_Control_WebServiceInformationPanel_WebServiceInformationPanel {
            get {
                return ((string)(this["Ground_Service_Control_WebServiceInformationPanel_WebServiceInformationPanel"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://airport-dko-services.azurewebsites.net/BaggageTractor.asmx")]
        public string Ground_Service_Control_BaggageTractor_BaggageTractor {
            get {
                return ((string)(this["Ground_Service_Control_BaggageTractor_BaggageTractor"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://airport-dko-metrological.azurewebsites.net/MetrologService.asmx")]
        public string Ground_Service_Control_MetrologService_MetrologService {
            get {
                return ((string)(this["Ground_Service_Control_MetrologService_MetrologService"]));
            }
        }
    }
}
