//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.34209.
// 
#pragma warning disable 1591

namespace Aircraft_Generator.PassengersWs {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WebServicePassengersGeneratorSoap", Namespace="http://tempuri.org/")]
    public partial class WebServicePassengersGenerator : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GenerateRandomPassengersOperationCompleted;
        
        private System.Threading.SendOrPostCallback GeneratePassengerOperationCompleted;
        
        private System.Threading.SendOrPostCallback PassengerBehaviorOperationCompleted;
        
        private System.Threading.SendOrPostCallback onPlaneOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetPassengersListOperationCompleted;
        
        private System.Threading.SendOrPostCallback ResetOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WebServicePassengersGenerator() {
            this.Url = global::Aircraft_Generator.Properties.Settings.Default.Aircraft_Generator_PassengersWs_WebServicePassengersGenerator;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GenerateRandomPassengersCompletedEventHandler GenerateRandomPassengersCompleted;
        
        /// <remarks/>
        public event GeneratePassengerCompletedEventHandler GeneratePassengerCompleted;
        
        /// <remarks/>
        public event PassengerBehaviorCompletedEventHandler PassengerBehaviorCompleted;
        
        /// <remarks/>
        public event onPlaneCompletedEventHandler onPlaneCompleted;
        
        /// <remarks/>
        public event GetPassengersListCompletedEventHandler GetPassengersListCompleted;
        
        /// <remarks/>
        public event ResetCompletedEventHandler ResetCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GenerateRandomPassengers", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void GenerateRandomPassengers(int count) {
            this.Invoke("GenerateRandomPassengers", new object[] {
                        count});
        }
        
        /// <remarks/>
        public void GenerateRandomPassengersAsync(int count) {
            this.GenerateRandomPassengersAsync(count, null);
        }
        
        /// <remarks/>
        public void GenerateRandomPassengersAsync(int count, object userState) {
            if ((this.GenerateRandomPassengersOperationCompleted == null)) {
                this.GenerateRandomPassengersOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGenerateRandomPassengersOperationCompleted);
            }
            this.InvokeAsync("GenerateRandomPassengers", new object[] {
                        count}, this.GenerateRandomPassengersOperationCompleted, userState);
        }
        
        private void OnGenerateRandomPassengersOperationCompleted(object arg) {
            if ((this.GenerateRandomPassengersCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GenerateRandomPassengersCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GeneratePassenger", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void GeneratePassenger(Food food, int baggage) {
            this.Invoke("GeneratePassenger", new object[] {
                        food,
                        baggage});
        }
        
        /// <remarks/>
        public void GeneratePassengerAsync(Food food, int baggage) {
            this.GeneratePassengerAsync(food, baggage, null);
        }
        
        /// <remarks/>
        public void GeneratePassengerAsync(Food food, int baggage, object userState) {
            if ((this.GeneratePassengerOperationCompleted == null)) {
                this.GeneratePassengerOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGeneratePassengerOperationCompleted);
            }
            this.InvokeAsync("GeneratePassenger", new object[] {
                        food,
                        baggage}, this.GeneratePassengerOperationCompleted, userState);
        }
        
        private void OnGeneratePassengerOperationCompleted(object arg) {
            if ((this.GeneratePassengerCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GeneratePassengerCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/PassengerBehavior", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void PassengerBehavior() {
            this.Invoke("PassengerBehavior", new object[0]);
        }
        
        /// <remarks/>
        public void PassengerBehaviorAsync() {
            this.PassengerBehaviorAsync(null);
        }
        
        /// <remarks/>
        public void PassengerBehaviorAsync(object userState) {
            if ((this.PassengerBehaviorOperationCompleted == null)) {
                this.PassengerBehaviorOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPassengerBehaviorOperationCompleted);
            }
            this.InvokeAsync("PassengerBehavior", new object[0], this.PassengerBehaviorOperationCompleted, userState);
        }
        
        private void OnPassengerBehaviorOperationCompleted(object arg) {
            if ((this.PassengerBehaviorCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PassengerBehaviorCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/onPlane", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool onPlane(System.Guid[] passengerId) {
            object[] results = this.Invoke("onPlane", new object[] {
                        passengerId});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void onPlaneAsync(System.Guid[] passengerId) {
            this.onPlaneAsync(passengerId, null);
        }
        
        /// <remarks/>
        public void onPlaneAsync(System.Guid[] passengerId, object userState) {
            if ((this.onPlaneOperationCompleted == null)) {
                this.onPlaneOperationCompleted = new System.Threading.SendOrPostCallback(this.OnonPlaneOperationCompleted);
            }
            this.InvokeAsync("onPlane", new object[] {
                        passengerId}, this.onPlaneOperationCompleted, userState);
        }
        
        private void OnonPlaneOperationCompleted(object arg) {
            if ((this.onPlaneCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.onPlaneCompleted(this, new onPlaneCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetPassengersList", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Passenger[] GetPassengersList() {
            object[] results = this.Invoke("GetPassengersList", new object[0]);
            return ((Passenger[])(results[0]));
        }
        
        /// <remarks/>
        public void GetPassengersListAsync() {
            this.GetPassengersListAsync(null);
        }
        
        /// <remarks/>
        public void GetPassengersListAsync(object userState) {
            if ((this.GetPassengersListOperationCompleted == null)) {
                this.GetPassengersListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetPassengersListOperationCompleted);
            }
            this.InvokeAsync("GetPassengersList", new object[0], this.GetPassengersListOperationCompleted, userState);
        }
        
        private void OnGetPassengersListOperationCompleted(object arg) {
            if ((this.GetPassengersListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetPassengersListCompleted(this, new GetPassengersListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Reset", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void Reset() {
            this.Invoke("Reset", new object[0]);
        }
        
        /// <remarks/>
        public void ResetAsync() {
            this.ResetAsync(null);
        }
        
        /// <remarks/>
        public void ResetAsync(object userState) {
            if ((this.ResetOperationCompleted == null)) {
                this.ResetOperationCompleted = new System.Threading.SendOrPostCallback(this.OnResetOperationCompleted);
            }
            this.InvokeAsync("Reset", new object[0], this.ResetOperationCompleted, userState);
        }
        
        private void OnResetOperationCompleted(object arg) {
            if ((this.ResetCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ResetCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public enum Food {
        
        /// <remarks/>
        Diabetic,
        
        /// <remarks/>
        Vegetarian,
        
        /// <remarks/>
        Children,
        
        /// <remarks/>
        LowCalorie,
        
        /// <remarks/>
        Default,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Passenger {
        
        private System.Guid idField;
        
        private PassengerState stateField;
        
        private Food preferFoodField;
        
        private int weightBaggageField;
        
        private Ticket ticketField;
        
        /// <remarks/>
        public System.Guid ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public PassengerState State {
            get {
                return this.stateField;
            }
            set {
                this.stateField = value;
            }
        }
        
        /// <remarks/>
        public Food PreferFood {
            get {
                return this.preferFoodField;
            }
            set {
                this.preferFoodField = value;
            }
        }
        
        /// <remarks/>
        public int WeightBaggage {
            get {
                return this.weightBaggageField;
            }
            set {
                this.weightBaggageField = value;
            }
        }
        
        /// <remarks/>
        public Ticket Ticket {
            get {
                return this.ticketField;
            }
            set {
                this.ticketField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public enum PassengerState {
        
        /// <remarks/>
        Created,
        
        /// <remarks/>
        Buy,
        
        /// <remarks/>
        Registered,
        
        /// <remarks/>
        Onboard,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Ticket {
        
        private System.Guid passengerIDField;
        
        private System.Guid flightIDField;
        
        private Class ticketClassField;
        
        /// <remarks/>
        public System.Guid PassengerID {
            get {
                return this.passengerIDField;
            }
            set {
                this.passengerIDField = value;
            }
        }
        
        /// <remarks/>
        public System.Guid FlightID {
            get {
                return this.flightIDField;
            }
            set {
                this.flightIDField = value;
            }
        }
        
        /// <remarks/>
        public Class TicketClass {
            get {
                return this.ticketClassField;
            }
            set {
                this.ticketClassField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public enum Class {
        
        /// <remarks/>
        Vip,
        
        /// <remarks/>
        Econom,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void GenerateRandomPassengersCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void GeneratePassengerCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void PassengerBehaviorCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void onPlaneCompletedEventHandler(object sender, onPlaneCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class onPlaneCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal onPlaneCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void GetPassengersListCompletedEventHandler(object sender, GetPassengersListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetPassengersListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetPassengersListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Passenger[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Passenger[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void ResetCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
}

#pragma warning restore 1591