//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aircraft_Generator_GUI.WSAircraftGenerator {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PlaneType", Namespace="DKO-Ariport-Aircraft-Generator")]
    public enum PlaneType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Airbus = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Jet = 1,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Plane", Namespace="DKO-Ariport-Aircraft-Generator")]
    [System.SerializableAttribute()]
    public partial class Plane : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.Guid IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        private Aircraft_Generator_GUI.WSAircraftGenerator.PlaneState StateField;
        
        private Aircraft_Generator_GUI.WSAircraftGenerator.PlaneType TypeField;
        
        private int FuelNeedField;
        
        private int MaxStandartPassengersField;
        
        private int MaxVipPassengersField;
        
        private bool HasArrivalPassengersField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Guid Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public Aircraft_Generator_GUI.WSAircraftGenerator.PlaneState State {
            get {
                return this.StateField;
            }
            set {
                if ((this.StateField.Equals(value) != true)) {
                    this.StateField = value;
                    this.RaisePropertyChanged("State");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public Aircraft_Generator_GUI.WSAircraftGenerator.PlaneType Type {
            get {
                return this.TypeField;
            }
            set {
                if ((this.TypeField.Equals(value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public int FuelNeed {
            get {
                return this.FuelNeedField;
            }
            set {
                if ((this.FuelNeedField.Equals(value) != true)) {
                    this.FuelNeedField = value;
                    this.RaisePropertyChanged("FuelNeed");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public int MaxStandartPassengers {
            get {
                return this.MaxStandartPassengersField;
            }
            set {
                if ((this.MaxStandartPassengersField.Equals(value) != true)) {
                    this.MaxStandartPassengersField = value;
                    this.RaisePropertyChanged("MaxStandartPassengers");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public int MaxVipPassengers {
            get {
                return this.MaxVipPassengersField;
            }
            set {
                if ((this.MaxVipPassengersField.Equals(value) != true)) {
                    this.MaxVipPassengersField = value;
                    this.RaisePropertyChanged("MaxVipPassengers");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public bool HasArrivalPassengers {
            get {
                return this.HasArrivalPassengersField;
            }
            set {
                if ((this.HasArrivalPassengersField.Equals(value) != true)) {
                    this.HasArrivalPassengersField = value;
                    this.RaisePropertyChanged("HasArrivalPassengers");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PlaneState", Namespace="DKO-Ariport-Aircraft-Generator")]
    public enum PlaneState : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Arrival = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Landing = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TaxingToServiceArea = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OnService = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TaxingToRunway = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Departed = 5,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="DKO-Ariport-Aircraft-Generator", ConfigurationName="WSAircraftGenerator.AircraftGeneratorSoap")]
    public interface AircraftGeneratorSoap {
        
        // CODEGEN: Generating message contract since element name name from namespace DKO-Ariport-Aircraft-Generator is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="DKO-Ariport-Aircraft-Generator/CreateNewPlane", ReplyAction="*")]
        Aircraft_Generator_GUI.WSAircraftGenerator.CreateNewPlaneResponse CreateNewPlane(Aircraft_Generator_GUI.WSAircraftGenerator.CreateNewPlaneRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="DKO-Ariport-Aircraft-Generator/CreateNewPlane", ReplyAction="*")]
        System.Threading.Tasks.Task<Aircraft_Generator_GUI.WSAircraftGenerator.CreateNewPlaneResponse> CreateNewPlaneAsync(Aircraft_Generator_GUI.WSAircraftGenerator.CreateNewPlaneRequest request);
        
        // CODEGEN: Generating message contract since element name GetAllPlanesResult from namespace DKO-Ariport-Aircraft-Generator is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="DKO-Ariport-Aircraft-Generator/GetAllPlanes", ReplyAction="*")]
        Aircraft_Generator_GUI.WSAircraftGenerator.GetAllPlanesResponse GetAllPlanes(Aircraft_Generator_GUI.WSAircraftGenerator.GetAllPlanesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="DKO-Ariport-Aircraft-Generator/GetAllPlanes", ReplyAction="*")]
        System.Threading.Tasks.Task<Aircraft_Generator_GUI.WSAircraftGenerator.GetAllPlanesResponse> GetAllPlanesAsync(Aircraft_Generator_GUI.WSAircraftGenerator.GetAllPlanesRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateNewPlaneRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateNewPlane", Namespace="DKO-Ariport-Aircraft-Generator", Order=0)]
        public Aircraft_Generator_GUI.WSAircraftGenerator.CreateNewPlaneRequestBody Body;
        
        public CreateNewPlaneRequest() {
        }
        
        public CreateNewPlaneRequest(Aircraft_Generator_GUI.WSAircraftGenerator.CreateNewPlaneRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="DKO-Ariport-Aircraft-Generator")]
    public partial class CreateNewPlaneRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string name;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public Aircraft_Generator_GUI.WSAircraftGenerator.PlaneType type;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int fuelNeed;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int maxStandartPassengers;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int maxVipPassengers;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public bool hasArrivalPassengers;
        
        public CreateNewPlaneRequestBody() {
        }
        
        public CreateNewPlaneRequestBody(string name, Aircraft_Generator_GUI.WSAircraftGenerator.PlaneType type, int fuelNeed, int maxStandartPassengers, int maxVipPassengers, bool hasArrivalPassengers) {
            this.name = name;
            this.type = type;
            this.fuelNeed = fuelNeed;
            this.maxStandartPassengers = maxStandartPassengers;
            this.maxVipPassengers = maxVipPassengers;
            this.hasArrivalPassengers = hasArrivalPassengers;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateNewPlaneResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateNewPlaneResponse", Namespace="DKO-Ariport-Aircraft-Generator", Order=0)]
        public Aircraft_Generator_GUI.WSAircraftGenerator.CreateNewPlaneResponseBody Body;
        
        public CreateNewPlaneResponse() {
        }
        
        public CreateNewPlaneResponse(Aircraft_Generator_GUI.WSAircraftGenerator.CreateNewPlaneResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="DKO-Ariport-Aircraft-Generator")]
    public partial class CreateNewPlaneResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool CreateNewPlaneResult;
        
        public CreateNewPlaneResponseBody() {
        }
        
        public CreateNewPlaneResponseBody(bool CreateNewPlaneResult) {
            this.CreateNewPlaneResult = CreateNewPlaneResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllPlanesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllPlanes", Namespace="DKO-Ariport-Aircraft-Generator", Order=0)]
        public Aircraft_Generator_GUI.WSAircraftGenerator.GetAllPlanesRequestBody Body;
        
        public GetAllPlanesRequest() {
        }
        
        public GetAllPlanesRequest(Aircraft_Generator_GUI.WSAircraftGenerator.GetAllPlanesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetAllPlanesRequestBody {
        
        public GetAllPlanesRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllPlanesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllPlanesResponse", Namespace="DKO-Ariport-Aircraft-Generator", Order=0)]
        public Aircraft_Generator_GUI.WSAircraftGenerator.GetAllPlanesResponseBody Body;
        
        public GetAllPlanesResponse() {
        }
        
        public GetAllPlanesResponse(Aircraft_Generator_GUI.WSAircraftGenerator.GetAllPlanesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="DKO-Ariport-Aircraft-Generator")]
    public partial class GetAllPlanesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Aircraft_Generator_GUI.WSAircraftGenerator.Plane[] GetAllPlanesResult;
        
        public GetAllPlanesResponseBody() {
        }
        
        public GetAllPlanesResponseBody(Aircraft_Generator_GUI.WSAircraftGenerator.Plane[] GetAllPlanesResult) {
            this.GetAllPlanesResult = GetAllPlanesResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AircraftGeneratorSoapChannel : Aircraft_Generator_GUI.WSAircraftGenerator.AircraftGeneratorSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AircraftGeneratorSoapClient : System.ServiceModel.ClientBase<Aircraft_Generator_GUI.WSAircraftGenerator.AircraftGeneratorSoap>, Aircraft_Generator_GUI.WSAircraftGenerator.AircraftGeneratorSoap {
        
        public AircraftGeneratorSoapClient() {
        }
        
        public AircraftGeneratorSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AircraftGeneratorSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AircraftGeneratorSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AircraftGeneratorSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Aircraft_Generator_GUI.WSAircraftGenerator.CreateNewPlaneResponse Aircraft_Generator_GUI.WSAircraftGenerator.AircraftGeneratorSoap.CreateNewPlane(Aircraft_Generator_GUI.WSAircraftGenerator.CreateNewPlaneRequest request) {
            return base.Channel.CreateNewPlane(request);
        }
        
        public bool CreateNewPlane(string name, Aircraft_Generator_GUI.WSAircraftGenerator.PlaneType type, int fuelNeed, int maxStandartPassengers, int maxVipPassengers, bool hasArrivalPassengers) {
            Aircraft_Generator_GUI.WSAircraftGenerator.CreateNewPlaneRequest inValue = new Aircraft_Generator_GUI.WSAircraftGenerator.CreateNewPlaneRequest();
            inValue.Body = new Aircraft_Generator_GUI.WSAircraftGenerator.CreateNewPlaneRequestBody();
            inValue.Body.name = name;
            inValue.Body.type = type;
            inValue.Body.fuelNeed = fuelNeed;
            inValue.Body.maxStandartPassengers = maxStandartPassengers;
            inValue.Body.maxVipPassengers = maxVipPassengers;
            inValue.Body.hasArrivalPassengers = hasArrivalPassengers;
            Aircraft_Generator_GUI.WSAircraftGenerator.CreateNewPlaneResponse retVal = ((Aircraft_Generator_GUI.WSAircraftGenerator.AircraftGeneratorSoap)(this)).CreateNewPlane(inValue);
            return retVal.Body.CreateNewPlaneResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Aircraft_Generator_GUI.WSAircraftGenerator.CreateNewPlaneResponse> Aircraft_Generator_GUI.WSAircraftGenerator.AircraftGeneratorSoap.CreateNewPlaneAsync(Aircraft_Generator_GUI.WSAircraftGenerator.CreateNewPlaneRequest request) {
            return base.Channel.CreateNewPlaneAsync(request);
        }
        
        public System.Threading.Tasks.Task<Aircraft_Generator_GUI.WSAircraftGenerator.CreateNewPlaneResponse> CreateNewPlaneAsync(string name, Aircraft_Generator_GUI.WSAircraftGenerator.PlaneType type, int fuelNeed, int maxStandartPassengers, int maxVipPassengers, bool hasArrivalPassengers) {
            Aircraft_Generator_GUI.WSAircraftGenerator.CreateNewPlaneRequest inValue = new Aircraft_Generator_GUI.WSAircraftGenerator.CreateNewPlaneRequest();
            inValue.Body = new Aircraft_Generator_GUI.WSAircraftGenerator.CreateNewPlaneRequestBody();
            inValue.Body.name = name;
            inValue.Body.type = type;
            inValue.Body.fuelNeed = fuelNeed;
            inValue.Body.maxStandartPassengers = maxStandartPassengers;
            inValue.Body.maxVipPassengers = maxVipPassengers;
            inValue.Body.hasArrivalPassengers = hasArrivalPassengers;
            return ((Aircraft_Generator_GUI.WSAircraftGenerator.AircraftGeneratorSoap)(this)).CreateNewPlaneAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Aircraft_Generator_GUI.WSAircraftGenerator.GetAllPlanesResponse Aircraft_Generator_GUI.WSAircraftGenerator.AircraftGeneratorSoap.GetAllPlanes(Aircraft_Generator_GUI.WSAircraftGenerator.GetAllPlanesRequest request) {
            return base.Channel.GetAllPlanes(request);
        }
        
        public Aircraft_Generator_GUI.WSAircraftGenerator.Plane[] GetAllPlanes() {
            Aircraft_Generator_GUI.WSAircraftGenerator.GetAllPlanesRequest inValue = new Aircraft_Generator_GUI.WSAircraftGenerator.GetAllPlanesRequest();
            inValue.Body = new Aircraft_Generator_GUI.WSAircraftGenerator.GetAllPlanesRequestBody();
            Aircraft_Generator_GUI.WSAircraftGenerator.GetAllPlanesResponse retVal = ((Aircraft_Generator_GUI.WSAircraftGenerator.AircraftGeneratorSoap)(this)).GetAllPlanes(inValue);
            return retVal.Body.GetAllPlanesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Aircraft_Generator_GUI.WSAircraftGenerator.GetAllPlanesResponse> Aircraft_Generator_GUI.WSAircraftGenerator.AircraftGeneratorSoap.GetAllPlanesAsync(Aircraft_Generator_GUI.WSAircraftGenerator.GetAllPlanesRequest request) {
            return base.Channel.GetAllPlanesAsync(request);
        }
        
        public System.Threading.Tasks.Task<Aircraft_Generator_GUI.WSAircraftGenerator.GetAllPlanesResponse> GetAllPlanesAsync() {
            Aircraft_Generator_GUI.WSAircraftGenerator.GetAllPlanesRequest inValue = new Aircraft_Generator_GUI.WSAircraftGenerator.GetAllPlanesRequest();
            inValue.Body = new Aircraft_Generator_GUI.WSAircraftGenerator.GetAllPlanesRequestBody();
            return ((Aircraft_Generator_GUI.WSAircraftGenerator.AircraftGeneratorSoap)(this)).GetAllPlanesAsync(inValue);
        }
    }
}
