//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebTicketSales.ServiceInformationPanel {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Flight", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    internal partial class Flight : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.Guid numberField;
        
        private WebTicketSales.ServiceInformationPanel.Cities cityField;
        
        private System.DateTime arrivalTimeField;
        
        private System.DateTime takeoffTimeField;
        
        private System.DateTime StartRegistrationTimeField;
        
        private System.DateTime EndRegistrationTimeField;
        
        private int EconomPassengersCountField;
        
        private int VipPassengersCountField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        internal System.Guid number {
            get {
                return this.numberField;
            }
            set {
                if ((this.numberField.Equals(value) != true)) {
                    this.numberField = value;
                    this.RaisePropertyChanged("number");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        internal WebTicketSales.ServiceInformationPanel.Cities city {
            get {
                return this.cityField;
            }
            set {
                if ((this.cityField.Equals(value) != true)) {
                    this.cityField = value;
                    this.RaisePropertyChanged("city");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        internal System.DateTime arrivalTime {
            get {
                return this.arrivalTimeField;
            }
            set {
                if ((this.arrivalTimeField.Equals(value) != true)) {
                    this.arrivalTimeField = value;
                    this.RaisePropertyChanged("arrivalTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        internal System.DateTime takeoffTime {
            get {
                return this.takeoffTimeField;
            }
            set {
                if ((this.takeoffTimeField.Equals(value) != true)) {
                    this.takeoffTimeField = value;
                    this.RaisePropertyChanged("takeoffTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        internal System.DateTime StartRegistrationTime {
            get {
                return this.StartRegistrationTimeField;
            }
            set {
                if ((this.StartRegistrationTimeField.Equals(value) != true)) {
                    this.StartRegistrationTimeField = value;
                    this.RaisePropertyChanged("StartRegistrationTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        internal System.DateTime EndRegistrationTime {
            get {
                return this.EndRegistrationTimeField;
            }
            set {
                if ((this.EndRegistrationTimeField.Equals(value) != true)) {
                    this.EndRegistrationTimeField = value;
                    this.RaisePropertyChanged("EndRegistrationTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        internal int EconomPassengersCount {
            get {
                return this.EconomPassengersCountField;
            }
            set {
                if ((this.EconomPassengersCountField.Equals(value) != true)) {
                    this.EconomPassengersCountField = value;
                    this.RaisePropertyChanged("EconomPassengersCount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        internal int VipPassengersCount {
            get {
                return this.VipPassengersCountField;
            }
            set {
                if ((this.VipPassengersCountField.Equals(value) != true)) {
                    this.VipPassengersCountField = value;
                    this.RaisePropertyChanged("VipPassengersCount");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Cities", Namespace="http://tempuri.org/")]
    internal enum Cities : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Tokyo = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Paris = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Rome = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NewYork = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Sydney = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Brasilia = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Antananarivo = 6,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceInformationPanel.WebServiceInformationPanelSoap")]
    internal interface WebServiceInformationPanelSoap {
        
        // CODEGEN: Generating message contract since element name GetFlightForPlaneResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetFlightForPlane", ReplyAction="*")]
        WebTicketSales.ServiceInformationPanel.GetFlightForPlaneResponse GetFlightForPlane(WebTicketSales.ServiceInformationPanel.GetFlightForPlaneRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetFlightForPlane", ReplyAction="*")]
        System.Threading.Tasks.Task<WebTicketSales.ServiceInformationPanel.GetFlightForPlaneResponse> GetFlightForPlaneAsync(WebTicketSales.ServiceInformationPanel.GetFlightForPlaneRequest request);
        
        // CODEGEN: Generating message contract since element name GetFlightsForRegistrationResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetFlightsForRegistration", ReplyAction="*")]
        WebTicketSales.ServiceInformationPanel.GetFlightsForRegistrationResponse GetFlightsForRegistration(WebTicketSales.ServiceInformationPanel.GetFlightsForRegistrationRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetFlightsForRegistration", ReplyAction="*")]
        System.Threading.Tasks.Task<WebTicketSales.ServiceInformationPanel.GetFlightsForRegistrationResponse> GetFlightsForRegistrationAsync(WebTicketSales.ServiceInformationPanel.GetFlightsForRegistrationRequest request);
        
        // CODEGEN: Generating message contract since element name GetFlightsForSalesResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetFlightsForSales", ReplyAction="*")]
        WebTicketSales.ServiceInformationPanel.GetFlightsForSalesResponse GetFlightsForSales(WebTicketSales.ServiceInformationPanel.GetFlightsForSalesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetFlightsForSales", ReplyAction="*")]
        System.Threading.Tasks.Task<WebTicketSales.ServiceInformationPanel.GetFlightsForSalesResponse> GetFlightsForSalesAsync(WebTicketSales.ServiceInformationPanel.GetFlightsForSalesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsFlightSoon", ReplyAction="*")]
        bool IsFlightSoon(System.Guid flightNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsFlightSoon", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> IsFlightSoonAsync(System.Guid flightNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsCheckInFinished", ReplyAction="*")]
        bool IsCheckInFinished(System.Guid flightNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsCheckInFinished", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> IsCheckInFinishedAsync(System.Guid flightNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CreateFlight", ReplyAction="*")]
        void CreateFlight(System.DateTime takeoffTime, WebTicketSales.ServiceInformationPanel.Cities city, int economPassengers, int vipPassengers);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CreateFlight", ReplyAction="*")]
        System.Threading.Tasks.Task CreateFlightAsync(System.DateTime takeoffTime, WebTicketSales.ServiceInformationPanel.Cities city, int economPassengers, int vipPassengers);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class GetFlightForPlaneRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetFlightForPlane", Namespace="http://tempuri.org/", Order=0)]
        public WebTicketSales.ServiceInformationPanel.GetFlightForPlaneRequestBody Body;
        
        public GetFlightForPlaneRequest() {
        }
        
        public GetFlightForPlaneRequest(WebTicketSales.ServiceInformationPanel.GetFlightForPlaneRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    internal partial class GetFlightForPlaneRequestBody {
        
        public GetFlightForPlaneRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class GetFlightForPlaneResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetFlightForPlaneResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebTicketSales.ServiceInformationPanel.GetFlightForPlaneResponseBody Body;
        
        public GetFlightForPlaneResponse() {
        }
        
        public GetFlightForPlaneResponse(WebTicketSales.ServiceInformationPanel.GetFlightForPlaneResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    internal partial class GetFlightForPlaneResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WebTicketSales.ServiceInformationPanel.Flight GetFlightForPlaneResult;
        
        public GetFlightForPlaneResponseBody() {
        }
        
        public GetFlightForPlaneResponseBody(WebTicketSales.ServiceInformationPanel.Flight GetFlightForPlaneResult) {
            this.GetFlightForPlaneResult = GetFlightForPlaneResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class GetFlightsForRegistrationRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetFlightsForRegistration", Namespace="http://tempuri.org/", Order=0)]
        public WebTicketSales.ServiceInformationPanel.GetFlightsForRegistrationRequestBody Body;
        
        public GetFlightsForRegistrationRequest() {
        }
        
        public GetFlightsForRegistrationRequest(WebTicketSales.ServiceInformationPanel.GetFlightsForRegistrationRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    internal partial class GetFlightsForRegistrationRequestBody {
        
        public GetFlightsForRegistrationRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class GetFlightsForRegistrationResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetFlightsForRegistrationResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebTicketSales.ServiceInformationPanel.GetFlightsForRegistrationResponseBody Body;
        
        public GetFlightsForRegistrationResponse() {
        }
        
        public GetFlightsForRegistrationResponse(WebTicketSales.ServiceInformationPanel.GetFlightsForRegistrationResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    internal partial class GetFlightsForRegistrationResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WebTicketSales.ServiceInformationPanel.Flight[] GetFlightsForRegistrationResult;
        
        public GetFlightsForRegistrationResponseBody() {
        }
        
        public GetFlightsForRegistrationResponseBody(WebTicketSales.ServiceInformationPanel.Flight[] GetFlightsForRegistrationResult) {
            this.GetFlightsForRegistrationResult = GetFlightsForRegistrationResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class GetFlightsForSalesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetFlightsForSales", Namespace="http://tempuri.org/", Order=0)]
        public WebTicketSales.ServiceInformationPanel.GetFlightsForSalesRequestBody Body;
        
        public GetFlightsForSalesRequest() {
        }
        
        public GetFlightsForSalesRequest(WebTicketSales.ServiceInformationPanel.GetFlightsForSalesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    internal partial class GetFlightsForSalesRequestBody {
        
        public GetFlightsForSalesRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class GetFlightsForSalesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetFlightsForSalesResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebTicketSales.ServiceInformationPanel.GetFlightsForSalesResponseBody Body;
        
        public GetFlightsForSalesResponse() {
        }
        
        public GetFlightsForSalesResponse(WebTicketSales.ServiceInformationPanel.GetFlightsForSalesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    internal partial class GetFlightsForSalesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WebTicketSales.ServiceInformationPanel.Flight[] GetFlightsForSalesResult;
        
        public GetFlightsForSalesResponseBody() {
        }
        
        public GetFlightsForSalesResponseBody(WebTicketSales.ServiceInformationPanel.Flight[] GetFlightsForSalesResult) {
            this.GetFlightsForSalesResult = GetFlightsForSalesResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    internal interface WebServiceInformationPanelSoapChannel : WebTicketSales.ServiceInformationPanel.WebServiceInformationPanelSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    internal partial class WebServiceInformationPanelSoapClient : System.ServiceModel.ClientBase<WebTicketSales.ServiceInformationPanel.WebServiceInformationPanelSoap>, WebTicketSales.ServiceInformationPanel.WebServiceInformationPanelSoap {
        
        public WebServiceInformationPanelSoapClient() {
        }
        
        public WebServiceInformationPanelSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceInformationPanelSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceInformationPanelSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceInformationPanelSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebTicketSales.ServiceInformationPanel.GetFlightForPlaneResponse WebTicketSales.ServiceInformationPanel.WebServiceInformationPanelSoap.GetFlightForPlane(WebTicketSales.ServiceInformationPanel.GetFlightForPlaneRequest request) {
            return base.Channel.GetFlightForPlane(request);
        }
        
        public WebTicketSales.ServiceInformationPanel.Flight GetFlightForPlane() {
            WebTicketSales.ServiceInformationPanel.GetFlightForPlaneRequest inValue = new WebTicketSales.ServiceInformationPanel.GetFlightForPlaneRequest();
            inValue.Body = new WebTicketSales.ServiceInformationPanel.GetFlightForPlaneRequestBody();
            WebTicketSales.ServiceInformationPanel.GetFlightForPlaneResponse retVal = ((WebTicketSales.ServiceInformationPanel.WebServiceInformationPanelSoap)(this)).GetFlightForPlane(inValue);
            return retVal.Body.GetFlightForPlaneResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebTicketSales.ServiceInformationPanel.GetFlightForPlaneResponse> WebTicketSales.ServiceInformationPanel.WebServiceInformationPanelSoap.GetFlightForPlaneAsync(WebTicketSales.ServiceInformationPanel.GetFlightForPlaneRequest request) {
            return base.Channel.GetFlightForPlaneAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebTicketSales.ServiceInformationPanel.GetFlightForPlaneResponse> GetFlightForPlaneAsync() {
            WebTicketSales.ServiceInformationPanel.GetFlightForPlaneRequest inValue = new WebTicketSales.ServiceInformationPanel.GetFlightForPlaneRequest();
            inValue.Body = new WebTicketSales.ServiceInformationPanel.GetFlightForPlaneRequestBody();
            return ((WebTicketSales.ServiceInformationPanel.WebServiceInformationPanelSoap)(this)).GetFlightForPlaneAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebTicketSales.ServiceInformationPanel.GetFlightsForRegistrationResponse WebTicketSales.ServiceInformationPanel.WebServiceInformationPanelSoap.GetFlightsForRegistration(WebTicketSales.ServiceInformationPanel.GetFlightsForRegistrationRequest request) {
            return base.Channel.GetFlightsForRegistration(request);
        }
        
        public WebTicketSales.ServiceInformationPanel.Flight[] GetFlightsForRegistration() {
            WebTicketSales.ServiceInformationPanel.GetFlightsForRegistrationRequest inValue = new WebTicketSales.ServiceInformationPanel.GetFlightsForRegistrationRequest();
            inValue.Body = new WebTicketSales.ServiceInformationPanel.GetFlightsForRegistrationRequestBody();
            WebTicketSales.ServiceInformationPanel.GetFlightsForRegistrationResponse retVal = ((WebTicketSales.ServiceInformationPanel.WebServiceInformationPanelSoap)(this)).GetFlightsForRegistration(inValue);
            return retVal.Body.GetFlightsForRegistrationResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebTicketSales.ServiceInformationPanel.GetFlightsForRegistrationResponse> WebTicketSales.ServiceInformationPanel.WebServiceInformationPanelSoap.GetFlightsForRegistrationAsync(WebTicketSales.ServiceInformationPanel.GetFlightsForRegistrationRequest request) {
            return base.Channel.GetFlightsForRegistrationAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebTicketSales.ServiceInformationPanel.GetFlightsForRegistrationResponse> GetFlightsForRegistrationAsync() {
            WebTicketSales.ServiceInformationPanel.GetFlightsForRegistrationRequest inValue = new WebTicketSales.ServiceInformationPanel.GetFlightsForRegistrationRequest();
            inValue.Body = new WebTicketSales.ServiceInformationPanel.GetFlightsForRegistrationRequestBody();
            return ((WebTicketSales.ServiceInformationPanel.WebServiceInformationPanelSoap)(this)).GetFlightsForRegistrationAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebTicketSales.ServiceInformationPanel.GetFlightsForSalesResponse WebTicketSales.ServiceInformationPanel.WebServiceInformationPanelSoap.GetFlightsForSales(WebTicketSales.ServiceInformationPanel.GetFlightsForSalesRequest request) {
            return base.Channel.GetFlightsForSales(request);
        }
        
        public WebTicketSales.ServiceInformationPanel.Flight[] GetFlightsForSales() {
            WebTicketSales.ServiceInformationPanel.GetFlightsForSalesRequest inValue = new WebTicketSales.ServiceInformationPanel.GetFlightsForSalesRequest();
            inValue.Body = new WebTicketSales.ServiceInformationPanel.GetFlightsForSalesRequestBody();
            WebTicketSales.ServiceInformationPanel.GetFlightsForSalesResponse retVal = ((WebTicketSales.ServiceInformationPanel.WebServiceInformationPanelSoap)(this)).GetFlightsForSales(inValue);
            return retVal.Body.GetFlightsForSalesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebTicketSales.ServiceInformationPanel.GetFlightsForSalesResponse> WebTicketSales.ServiceInformationPanel.WebServiceInformationPanelSoap.GetFlightsForSalesAsync(WebTicketSales.ServiceInformationPanel.GetFlightsForSalesRequest request) {
            return base.Channel.GetFlightsForSalesAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebTicketSales.ServiceInformationPanel.GetFlightsForSalesResponse> GetFlightsForSalesAsync() {
            WebTicketSales.ServiceInformationPanel.GetFlightsForSalesRequest inValue = new WebTicketSales.ServiceInformationPanel.GetFlightsForSalesRequest();
            inValue.Body = new WebTicketSales.ServiceInformationPanel.GetFlightsForSalesRequestBody();
            return ((WebTicketSales.ServiceInformationPanel.WebServiceInformationPanelSoap)(this)).GetFlightsForSalesAsync(inValue);
        }
        
        public bool IsFlightSoon(System.Guid flightNumber) {
            return base.Channel.IsFlightSoon(flightNumber);
        }
        
        public System.Threading.Tasks.Task<bool> IsFlightSoonAsync(System.Guid flightNumber) {
            return base.Channel.IsFlightSoonAsync(flightNumber);
        }
        
        public bool IsCheckInFinished(System.Guid flightNumber) {
            return base.Channel.IsCheckInFinished(flightNumber);
        }
        
        public System.Threading.Tasks.Task<bool> IsCheckInFinishedAsync(System.Guid flightNumber) {
            return base.Channel.IsCheckInFinishedAsync(flightNumber);
        }
        
        public void CreateFlight(System.DateTime takeoffTime, WebTicketSales.ServiceInformationPanel.Cities city, int economPassengers, int vipPassengers) {
            base.Channel.CreateFlight(takeoffTime, city, economPassengers, vipPassengers);
        }
        
        public System.Threading.Tasks.Task CreateFlightAsync(System.DateTime takeoffTime, WebTicketSales.ServiceInformationPanel.Cities city, int economPassengers, int vipPassengers) {
            return base.Channel.CreateFlightAsync(takeoffTime, city, economPassengers, vipPassengers);
        }
    }
}
