//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebCheckIn.ServiceReferenceTicketSales {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Ticket", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Ticket : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.Guid PassengerIDField;
        
        private System.Guid FlightIDField;
        
        private WebCheckIn.ServiceReferenceTicketSales.Class TicketClassField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        internal System.Guid PassengerID {
            get {
                return this.PassengerIDField;
            }
            set {
                if ((this.PassengerIDField.Equals(value) != true)) {
                    this.PassengerIDField = value;
                    this.RaisePropertyChanged("PassengerID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        internal System.Guid FlightID {
            get {
                return this.FlightIDField;
            }
            set {
                if ((this.FlightIDField.Equals(value) != true)) {
                    this.FlightIDField = value;
                    this.RaisePropertyChanged("FlightID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        internal WebCheckIn.ServiceReferenceTicketSales.Class TicketClass {
            get {
                return this.TicketClassField;
            }
            set {
                if ((this.TicketClassField.Equals(value) != true)) {
                    this.TicketClassField = value;
                    this.RaisePropertyChanged("TicketClass");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Class", Namespace="http://tempuri.org/")]
    internal enum Class : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Vip = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Econom = 1,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceTicketSales.WebServiceTicketSalesSoap")]
    internal interface WebServiceTicketSalesSoap {
        
        // CODEGEN: Generating message contract since element name BuyTicketResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BuyTicket", ReplyAction="*")]
        WebCheckIn.ServiceReferenceTicketSales.BuyTicketResponse BuyTicket(WebCheckIn.ServiceReferenceTicketSales.BuyTicketRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BuyTicket", ReplyAction="*")]
        System.Threading.Tasks.Task<WebCheckIn.ServiceReferenceTicketSales.BuyTicketResponse> BuyTicketAsync(WebCheckIn.ServiceReferenceTicketSales.BuyTicketRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReturnTicket", ReplyAction="*")]
        bool ReturnTicket(System.Guid passengerId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReturnTicket", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> ReturnTicketAsync(System.Guid passengerId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CheckTicket", ReplyAction="*")]
        bool CheckTicket(System.Guid passengerid, System.Guid fligthid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CheckTicket", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> CheckTicketAsync(System.Guid passengerid, System.Guid fligthid);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class BuyTicketRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="BuyTicket", Namespace="http://tempuri.org/", Order=0)]
        public WebCheckIn.ServiceReferenceTicketSales.BuyTicketRequestBody Body;
        
        public BuyTicketRequest() {
        }
        
        public BuyTicketRequest(WebCheckIn.ServiceReferenceTicketSales.BuyTicketRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    internal partial class BuyTicketRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public System.Guid passengerId;
        
        public BuyTicketRequestBody() {
        }
        
        public BuyTicketRequestBody(System.Guid passengerId) {
            this.passengerId = passengerId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class BuyTicketResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="BuyTicketResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebCheckIn.ServiceReferenceTicketSales.BuyTicketResponseBody Body;
        
        public BuyTicketResponse() {
        }
        
        public BuyTicketResponse(WebCheckIn.ServiceReferenceTicketSales.BuyTicketResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    internal partial class BuyTicketResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WebCheckIn.ServiceReferenceTicketSales.Ticket BuyTicketResult;
        
        public BuyTicketResponseBody() {
        }
        
        public BuyTicketResponseBody(WebCheckIn.ServiceReferenceTicketSales.Ticket BuyTicketResult) {
            this.BuyTicketResult = BuyTicketResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    internal interface WebServiceTicketSalesSoapChannel : WebCheckIn.ServiceReferenceTicketSales.WebServiceTicketSalesSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    internal partial class WebServiceTicketSalesSoapClient : System.ServiceModel.ClientBase<WebCheckIn.ServiceReferenceTicketSales.WebServiceTicketSalesSoap>, WebCheckIn.ServiceReferenceTicketSales.WebServiceTicketSalesSoap {
        
        public WebServiceTicketSalesSoapClient() {
        }
        
        public WebServiceTicketSalesSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceTicketSalesSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceTicketSalesSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceTicketSalesSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebCheckIn.ServiceReferenceTicketSales.BuyTicketResponse WebCheckIn.ServiceReferenceTicketSales.WebServiceTicketSalesSoap.BuyTicket(WebCheckIn.ServiceReferenceTicketSales.BuyTicketRequest request) {
            return base.Channel.BuyTicket(request);
        }
        
        public WebCheckIn.ServiceReferenceTicketSales.Ticket BuyTicket(System.Guid passengerId) {
            WebCheckIn.ServiceReferenceTicketSales.BuyTicketRequest inValue = new WebCheckIn.ServiceReferenceTicketSales.BuyTicketRequest();
            inValue.Body = new WebCheckIn.ServiceReferenceTicketSales.BuyTicketRequestBody();
            inValue.Body.passengerId = passengerId;
            WebCheckIn.ServiceReferenceTicketSales.BuyTicketResponse retVal = ((WebCheckIn.ServiceReferenceTicketSales.WebServiceTicketSalesSoap)(this)).BuyTicket(inValue);
            return retVal.Body.BuyTicketResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebCheckIn.ServiceReferenceTicketSales.BuyTicketResponse> WebCheckIn.ServiceReferenceTicketSales.WebServiceTicketSalesSoap.BuyTicketAsync(WebCheckIn.ServiceReferenceTicketSales.BuyTicketRequest request) {
            return base.Channel.BuyTicketAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebCheckIn.ServiceReferenceTicketSales.BuyTicketResponse> BuyTicketAsync(System.Guid passengerId) {
            WebCheckIn.ServiceReferenceTicketSales.BuyTicketRequest inValue = new WebCheckIn.ServiceReferenceTicketSales.BuyTicketRequest();
            inValue.Body = new WebCheckIn.ServiceReferenceTicketSales.BuyTicketRequestBody();
            inValue.Body.passengerId = passengerId;
            return ((WebCheckIn.ServiceReferenceTicketSales.WebServiceTicketSalesSoap)(this)).BuyTicketAsync(inValue);
        }
        
        public bool ReturnTicket(System.Guid passengerId) {
            return base.Channel.ReturnTicket(passengerId);
        }
        
        public System.Threading.Tasks.Task<bool> ReturnTicketAsync(System.Guid passengerId) {
            return base.Channel.ReturnTicketAsync(passengerId);
        }
        
        public bool CheckTicket(System.Guid passengerid, System.Guid fligthid) {
            return base.Channel.CheckTicket(passengerid, fligthid);
        }
        
        public System.Threading.Tasks.Task<bool> CheckTicketAsync(System.Guid passengerid, System.Guid fligthid) {
            return base.Channel.CheckTicketAsync(passengerid, fligthid);
        }
    }
}
