//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ground_Service_Control.AircraftGenerator {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PlaneType", Namespace="DKO-Ariport-Aircraft-Generator")]
    public enum PlaneType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Airbus = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Jet = 1,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Plane", Namespace="DKO-Ariport-Aircraft-Generator")]
    [System.SerializableAttribute()]
    public partial class Plane : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.Guid IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Ground_Service_Control.AircraftGenerator.Flight FlightField;
        
        private Ground_Service_Control.AircraftGenerator.PlaneState StateField;
        
        private Ground_Service_Control.AircraftGenerator.PlaneType TypeField;
        
        private int FuelNeedField;
        
        private int MaxStandartPassengersField;
        
        private int MaxVipPassengersField;
        
        private bool HasArrivalPassengersField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Guid Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public Ground_Service_Control.AircraftGenerator.Flight Flight {
            get {
                return this.FlightField;
            }
            set {
                if ((object.ReferenceEquals(this.FlightField, value) != true)) {
                    this.FlightField = value;
                    this.RaisePropertyChanged("Flight");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public Ground_Service_Control.AircraftGenerator.PlaneState State {
            get {
                return this.StateField;
            }
            set {
                if ((this.StateField.Equals(value) != true)) {
                    this.StateField = value;
                    this.RaisePropertyChanged("State");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public Ground_Service_Control.AircraftGenerator.PlaneType Type {
            get {
                return this.TypeField;
            }
            set {
                if ((this.TypeField.Equals(value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public int FuelNeed {
            get {
                return this.FuelNeedField;
            }
            set {
                if ((this.FuelNeedField.Equals(value) != true)) {
                    this.FuelNeedField = value;
                    this.RaisePropertyChanged("FuelNeed");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public int MaxStandartPassengers {
            get {
                return this.MaxStandartPassengersField;
            }
            set {
                if ((this.MaxStandartPassengersField.Equals(value) != true)) {
                    this.MaxStandartPassengersField = value;
                    this.RaisePropertyChanged("MaxStandartPassengers");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public int MaxVipPassengers {
            get {
                return this.MaxVipPassengersField;
            }
            set {
                if ((this.MaxVipPassengersField.Equals(value) != true)) {
                    this.MaxVipPassengersField = value;
                    this.RaisePropertyChanged("MaxVipPassengers");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public bool HasArrivalPassengers {
            get {
                return this.HasArrivalPassengersField;
            }
            set {
                if ((this.HasArrivalPassengersField.Equals(value) != true)) {
                    this.HasArrivalPassengersField = value;
                    this.RaisePropertyChanged("HasArrivalPassengers");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Flight", Namespace="DKO-Ariport-Aircraft-Generator")]
    [System.SerializableAttribute()]
    public partial class Flight : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int FlightNumberField;
        
        private Ground_Service_Control.AircraftGenerator.City CityField;
        
        private System.DateTime ArrivalTimeField;
        
        private System.DateTime DepartureTimeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int FlightNumber {
            get {
                return this.FlightNumberField;
            }
            set {
                if ((this.FlightNumberField.Equals(value) != true)) {
                    this.FlightNumberField = value;
                    this.RaisePropertyChanged("FlightNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public Ground_Service_Control.AircraftGenerator.City City {
            get {
                return this.CityField;
            }
            set {
                if ((this.CityField.Equals(value) != true)) {
                    this.CityField = value;
                    this.RaisePropertyChanged("City");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public System.DateTime ArrivalTime {
            get {
                return this.ArrivalTimeField;
            }
            set {
                if ((this.ArrivalTimeField.Equals(value) != true)) {
                    this.ArrivalTimeField = value;
                    this.RaisePropertyChanged("ArrivalTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public System.DateTime DepartureTime {
            get {
                return this.DepartureTimeField;
            }
            set {
                if ((this.DepartureTimeField.Equals(value) != true)) {
                    this.DepartureTimeField = value;
                    this.RaisePropertyChanged("DepartureTime");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PlaneState", Namespace="DKO-Ariport-Aircraft-Generator")]
    public enum PlaneState : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Arrival = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Landing = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TaxingToServiceArea = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OnService = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TaxingToRunway = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Departed = 5,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="City", Namespace="DKO-Ariport-Aircraft-Generator")]
    public enum City : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Tokyo = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Paris = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Rome = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NewYork = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Sydney = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Brasilia = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Antananarivo = 6,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfGuid", Namespace="DKO-Ariport-Aircraft-Generator", ItemName="guid")]
    [System.SerializableAttribute()]
    public class ArrayOfGuid : System.Collections.Generic.List<System.Guid> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="DKO-Ariport-Aircraft-Generator", ConfigurationName="AircraftGenerator.AircraftGeneratorSoap")]
    public interface AircraftGeneratorSoap {
        
        // CODEGEN: Generating message contract since element name name from namespace DKO-Ariport-Aircraft-Generator is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="DKO-Ariport-Aircraft-Generator/CreateNewPlane", ReplyAction="*")]
        Ground_Service_Control.AircraftGenerator.CreateNewPlaneResponse CreateNewPlane(Ground_Service_Control.AircraftGenerator.CreateNewPlaneRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="DKO-Ariport-Aircraft-Generator/CreateNewPlane", ReplyAction="*")]
        System.Threading.Tasks.Task<Ground_Service_Control.AircraftGenerator.CreateNewPlaneResponse> CreateNewPlaneAsync(Ground_Service_Control.AircraftGenerator.CreateNewPlaneRequest request);
        
        // CODEGEN: Generating message contract since element name GetAllPlanesResult from namespace DKO-Ariport-Aircraft-Generator is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="DKO-Ariport-Aircraft-Generator/GetAllPlanes", ReplyAction="*")]
        Ground_Service_Control.AircraftGenerator.GetAllPlanesResponse GetAllPlanes(Ground_Service_Control.AircraftGenerator.GetAllPlanesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="DKO-Ariport-Aircraft-Generator/GetAllPlanes", ReplyAction="*")]
        System.Threading.Tasks.Task<Ground_Service_Control.AircraftGenerator.GetAllPlanesResponse> GetAllPlanesAsync(Ground_Service_Control.AircraftGenerator.GetAllPlanesRequest request);
        
        // CODEGEN: Generating message contract since element name passengersList from namespace DKO-Ariport-Aircraft-Generator is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="DKO-Ariport-Aircraft-Generator/CheckInPassengers", ReplyAction="*")]
        Ground_Service_Control.AircraftGenerator.CheckInPassengersResponse CheckInPassengers(Ground_Service_Control.AircraftGenerator.CheckInPassengersRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="DKO-Ariport-Aircraft-Generator/CheckInPassengers", ReplyAction="*")]
        System.Threading.Tasks.Task<Ground_Service_Control.AircraftGenerator.CheckInPassengersResponse> CheckInPassengersAsync(Ground_Service_Control.AircraftGenerator.CheckInPassengersRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateNewPlaneRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateNewPlane", Namespace="DKO-Ariport-Aircraft-Generator", Order=0)]
        public Ground_Service_Control.AircraftGenerator.CreateNewPlaneRequestBody Body;
        
        public CreateNewPlaneRequest() {
        }
        
        public CreateNewPlaneRequest(Ground_Service_Control.AircraftGenerator.CreateNewPlaneRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="DKO-Ariport-Aircraft-Generator")]
    public partial class CreateNewPlaneRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string name;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public Ground_Service_Control.AircraftGenerator.PlaneType type;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int fuelNeed;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int maxStandartPassengers;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int maxVipPassengers;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public bool hasArrivalPassengers;
        
        public CreateNewPlaneRequestBody() {
        }
        
        public CreateNewPlaneRequestBody(string name, Ground_Service_Control.AircraftGenerator.PlaneType type, int fuelNeed, int maxStandartPassengers, int maxVipPassengers, bool hasArrivalPassengers) {
            this.name = name;
            this.type = type;
            this.fuelNeed = fuelNeed;
            this.maxStandartPassengers = maxStandartPassengers;
            this.maxVipPassengers = maxVipPassengers;
            this.hasArrivalPassengers = hasArrivalPassengers;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateNewPlaneResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateNewPlaneResponse", Namespace="DKO-Ariport-Aircraft-Generator", Order=0)]
        public Ground_Service_Control.AircraftGenerator.CreateNewPlaneResponseBody Body;
        
        public CreateNewPlaneResponse() {
        }
        
        public CreateNewPlaneResponse(Ground_Service_Control.AircraftGenerator.CreateNewPlaneResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="DKO-Ariport-Aircraft-Generator")]
    public partial class CreateNewPlaneResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool CreateNewPlaneResult;
        
        public CreateNewPlaneResponseBody() {
        }
        
        public CreateNewPlaneResponseBody(bool CreateNewPlaneResult) {
            this.CreateNewPlaneResult = CreateNewPlaneResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllPlanesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllPlanes", Namespace="DKO-Ariport-Aircraft-Generator", Order=0)]
        public Ground_Service_Control.AircraftGenerator.GetAllPlanesRequestBody Body;
        
        public GetAllPlanesRequest() {
        }
        
        public GetAllPlanesRequest(Ground_Service_Control.AircraftGenerator.GetAllPlanesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetAllPlanesRequestBody {
        
        public GetAllPlanesRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllPlanesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllPlanesResponse", Namespace="DKO-Ariport-Aircraft-Generator", Order=0)]
        public Ground_Service_Control.AircraftGenerator.GetAllPlanesResponseBody Body;
        
        public GetAllPlanesResponse() {
        }
        
        public GetAllPlanesResponse(Ground_Service_Control.AircraftGenerator.GetAllPlanesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="DKO-Ariport-Aircraft-Generator")]
    public partial class GetAllPlanesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Ground_Service_Control.AircraftGenerator.Plane[] GetAllPlanesResult;
        
        public GetAllPlanesResponseBody() {
        }
        
        public GetAllPlanesResponseBody(Ground_Service_Control.AircraftGenerator.Plane[] GetAllPlanesResult) {
            this.GetAllPlanesResult = GetAllPlanesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CheckInPassengersRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CheckInPassengers", Namespace="DKO-Ariport-Aircraft-Generator", Order=0)]
        public Ground_Service_Control.AircraftGenerator.CheckInPassengersRequestBody Body;
        
        public CheckInPassengersRequest() {
        }
        
        public CheckInPassengersRequest(Ground_Service_Control.AircraftGenerator.CheckInPassengersRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="DKO-Ariport-Aircraft-Generator")]
    public partial class CheckInPassengersRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Ground_Service_Control.AircraftGenerator.ArrayOfGuid passengersList;
        
        public CheckInPassengersRequestBody() {
        }
        
        public CheckInPassengersRequestBody(Ground_Service_Control.AircraftGenerator.ArrayOfGuid passengersList) {
            this.passengersList = passengersList;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CheckInPassengersResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CheckInPassengersResponse", Namespace="DKO-Ariport-Aircraft-Generator", Order=0)]
        public Ground_Service_Control.AircraftGenerator.CheckInPassengersResponseBody Body;
        
        public CheckInPassengersResponse() {
        }
        
        public CheckInPassengersResponse(Ground_Service_Control.AircraftGenerator.CheckInPassengersResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="DKO-Ariport-Aircraft-Generator")]
    public partial class CheckInPassengersResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool CheckInPassengersResult;
        
        public CheckInPassengersResponseBody() {
        }
        
        public CheckInPassengersResponseBody(bool CheckInPassengersResult) {
            this.CheckInPassengersResult = CheckInPassengersResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AircraftGeneratorSoapChannel : Ground_Service_Control.AircraftGenerator.AircraftGeneratorSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AircraftGeneratorSoapClient : System.ServiceModel.ClientBase<Ground_Service_Control.AircraftGenerator.AircraftGeneratorSoap>, Ground_Service_Control.AircraftGenerator.AircraftGeneratorSoap {
        
        public AircraftGeneratorSoapClient() {
        }
        
        public AircraftGeneratorSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AircraftGeneratorSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AircraftGeneratorSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AircraftGeneratorSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Ground_Service_Control.AircraftGenerator.CreateNewPlaneResponse Ground_Service_Control.AircraftGenerator.AircraftGeneratorSoap.CreateNewPlane(Ground_Service_Control.AircraftGenerator.CreateNewPlaneRequest request) {
            return base.Channel.CreateNewPlane(request);
        }
        
        public bool CreateNewPlane(string name, Ground_Service_Control.AircraftGenerator.PlaneType type, int fuelNeed, int maxStandartPassengers, int maxVipPassengers, bool hasArrivalPassengers) {
            Ground_Service_Control.AircraftGenerator.CreateNewPlaneRequest inValue = new Ground_Service_Control.AircraftGenerator.CreateNewPlaneRequest();
            inValue.Body = new Ground_Service_Control.AircraftGenerator.CreateNewPlaneRequestBody();
            inValue.Body.name = name;
            inValue.Body.type = type;
            inValue.Body.fuelNeed = fuelNeed;
            inValue.Body.maxStandartPassengers = maxStandartPassengers;
            inValue.Body.maxVipPassengers = maxVipPassengers;
            inValue.Body.hasArrivalPassengers = hasArrivalPassengers;
            Ground_Service_Control.AircraftGenerator.CreateNewPlaneResponse retVal = ((Ground_Service_Control.AircraftGenerator.AircraftGeneratorSoap)(this)).CreateNewPlane(inValue);
            return retVal.Body.CreateNewPlaneResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Ground_Service_Control.AircraftGenerator.CreateNewPlaneResponse> Ground_Service_Control.AircraftGenerator.AircraftGeneratorSoap.CreateNewPlaneAsync(Ground_Service_Control.AircraftGenerator.CreateNewPlaneRequest request) {
            return base.Channel.CreateNewPlaneAsync(request);
        }
        
        public System.Threading.Tasks.Task<Ground_Service_Control.AircraftGenerator.CreateNewPlaneResponse> CreateNewPlaneAsync(string name, Ground_Service_Control.AircraftGenerator.PlaneType type, int fuelNeed, int maxStandartPassengers, int maxVipPassengers, bool hasArrivalPassengers) {
            Ground_Service_Control.AircraftGenerator.CreateNewPlaneRequest inValue = new Ground_Service_Control.AircraftGenerator.CreateNewPlaneRequest();
            inValue.Body = new Ground_Service_Control.AircraftGenerator.CreateNewPlaneRequestBody();
            inValue.Body.name = name;
            inValue.Body.type = type;
            inValue.Body.fuelNeed = fuelNeed;
            inValue.Body.maxStandartPassengers = maxStandartPassengers;
            inValue.Body.maxVipPassengers = maxVipPassengers;
            inValue.Body.hasArrivalPassengers = hasArrivalPassengers;
            return ((Ground_Service_Control.AircraftGenerator.AircraftGeneratorSoap)(this)).CreateNewPlaneAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Ground_Service_Control.AircraftGenerator.GetAllPlanesResponse Ground_Service_Control.AircraftGenerator.AircraftGeneratorSoap.GetAllPlanes(Ground_Service_Control.AircraftGenerator.GetAllPlanesRequest request) {
            return base.Channel.GetAllPlanes(request);
        }
        
        public Ground_Service_Control.AircraftGenerator.Plane[] GetAllPlanes() {
            Ground_Service_Control.AircraftGenerator.GetAllPlanesRequest inValue = new Ground_Service_Control.AircraftGenerator.GetAllPlanesRequest();
            inValue.Body = new Ground_Service_Control.AircraftGenerator.GetAllPlanesRequestBody();
            Ground_Service_Control.AircraftGenerator.GetAllPlanesResponse retVal = ((Ground_Service_Control.AircraftGenerator.AircraftGeneratorSoap)(this)).GetAllPlanes(inValue);
            return retVal.Body.GetAllPlanesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Ground_Service_Control.AircraftGenerator.GetAllPlanesResponse> Ground_Service_Control.AircraftGenerator.AircraftGeneratorSoap.GetAllPlanesAsync(Ground_Service_Control.AircraftGenerator.GetAllPlanesRequest request) {
            return base.Channel.GetAllPlanesAsync(request);
        }
        
        public System.Threading.Tasks.Task<Ground_Service_Control.AircraftGenerator.GetAllPlanesResponse> GetAllPlanesAsync() {
            Ground_Service_Control.AircraftGenerator.GetAllPlanesRequest inValue = new Ground_Service_Control.AircraftGenerator.GetAllPlanesRequest();
            inValue.Body = new Ground_Service_Control.AircraftGenerator.GetAllPlanesRequestBody();
            return ((Ground_Service_Control.AircraftGenerator.AircraftGeneratorSoap)(this)).GetAllPlanesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Ground_Service_Control.AircraftGenerator.CheckInPassengersResponse Ground_Service_Control.AircraftGenerator.AircraftGeneratorSoap.CheckInPassengers(Ground_Service_Control.AircraftGenerator.CheckInPassengersRequest request) {
            return base.Channel.CheckInPassengers(request);
        }
        
        public bool CheckInPassengers(Ground_Service_Control.AircraftGenerator.ArrayOfGuid passengersList) {
            Ground_Service_Control.AircraftGenerator.CheckInPassengersRequest inValue = new Ground_Service_Control.AircraftGenerator.CheckInPassengersRequest();
            inValue.Body = new Ground_Service_Control.AircraftGenerator.CheckInPassengersRequestBody();
            inValue.Body.passengersList = passengersList;
            Ground_Service_Control.AircraftGenerator.CheckInPassengersResponse retVal = ((Ground_Service_Control.AircraftGenerator.AircraftGeneratorSoap)(this)).CheckInPassengers(inValue);
            return retVal.Body.CheckInPassengersResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Ground_Service_Control.AircraftGenerator.CheckInPassengersResponse> Ground_Service_Control.AircraftGenerator.AircraftGeneratorSoap.CheckInPassengersAsync(Ground_Service_Control.AircraftGenerator.CheckInPassengersRequest request) {
            return base.Channel.CheckInPassengersAsync(request);
        }
        
        public System.Threading.Tasks.Task<Ground_Service_Control.AircraftGenerator.CheckInPassengersResponse> CheckInPassengersAsync(Ground_Service_Control.AircraftGenerator.ArrayOfGuid passengersList) {
            Ground_Service_Control.AircraftGenerator.CheckInPassengersRequest inValue = new Ground_Service_Control.AircraftGenerator.CheckInPassengersRequest();
            inValue.Body = new Ground_Service_Control.AircraftGenerator.CheckInPassengersRequestBody();
            inValue.Body.passengersList = passengersList;
            return ((Ground_Service_Control.AircraftGenerator.AircraftGeneratorSoap)(this)).CheckInPassengersAsync(inValue);
        }
    }
}
