using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using WebApplication1.Logic;

namespace WebApplication1.Bidlokod
{
    public static class MyRoute
    {
        public static List<Route> GetRoute()
        {
            //Из файла
            return new List<Route>
            {
                new Route {
                    From = new Location { Position = new CoordinateTuple { X = 4, Y = 13}, MapObj = new MapObject { Type = MapObjectType.ServiceArea, number = 1} },
                    To = new Location { Position =  new CoordinateTuple { X = 4, Y = 2}, MapObj = new MapObject { Type = MapObjectType.Runway, number = 1 } },
                    Points = new List<CoordinateTuple> { new CoordinateTuple { X = 4, Y = 12},
                                                         new CoordinateTuple { X = 4, Y = 11},
                                                         new CoordinateTuple { X = 4, Y = 10},
                                                         new CoordinateTuple { X = 4, Y = 9},
                                                         new CoordinateTuple { X = 4, Y = 8},
                                                         new CoordinateTuple { X = 4, Y = 7},
                                                         new CoordinateTuple { X = 4, Y = 6},
                                                         new CoordinateTuple { X = 4, Y = 5},
                                                         new CoordinateTuple { X = 4, Y = 4},
                                                         new CoordinateTuple { X = 4, Y = 3},
                                                       }
                } ,
                new Route {
                    From = new Location { Position = new CoordinateTuple { X = 32, Y = 13}, MapObj = new MapObject { Type = MapObjectType.Garage, number = 1} },
                    To = new Location { Position =  new CoordinateTuple { X = 31, Y = 2}, MapObj = new MapObject { Type = MapObjectType.Runway, number = 2 } },
                    Points = new List<CoordinateTuple> { new CoordinateTuple { X = 31, Y = 13},
                                                         new CoordinateTuple { X = 31, Y = 12},
                                                         new CoordinateTuple { X = 31, Y = 11},
                                                         new CoordinateTuple { X = 31, Y = 10},
                                                         new CoordinateTuple { X = 31, Y = 9},
                                                         new CoordinateTuple { X = 31, Y = 8},
                                                         new CoordinateTuple { X = 31, Y = 7},
                                                         new CoordinateTuple { X = 31, Y = 6},
                                                         new CoordinateTuple { X = 31, Y = 5},
                                                         new CoordinateTuple { X = 31, Y = 4},
                                                         new CoordinateTuple { X = 31, Y = 3},
                                                       }
                } ,
                new Route {
                    From = new Location { Position = new CoordinateTuple { X = 27, Y = 16}, MapObj = new MapObject { Type = MapObjectType.Airport, number = 1} },
                    To = new Location { Position =  new CoordinateTuple { X = 31, Y = 2}, MapObj = new MapObject { Type = MapObjectType.Runway, number = 2 } },
                    Points = new List<CoordinateTuple> { new CoordinateTuple { X = 27, Y = 15},
                                                         new CoordinateTuple { X = 27, Y = 14},
                                                         new CoordinateTuple { X = 27, Y = 13},
                                                         new CoordinateTuple { X = 27, Y = 12},
                                                         new CoordinateTuple { X = 27, Y = 11},
                                                         new CoordinateTuple { X = 27, Y = 10},
                                                         new CoordinateTuple { X = 28, Y = 10},
                                                         new CoordinateTuple { X = 29, Y = 10},
                                                         new CoordinateTuple { X = 30, Y = 10},
                                                         new CoordinateTuple { X = 31, Y = 10},
                                                         new CoordinateTuple { X = 31, Y = 9},
                                                         new CoordinateTuple { X = 31, Y = 8},
                                                         new CoordinateTuple { X = 31, Y = 7},
                                                         new CoordinateTuple { X = 31, Y = 6},
                                                         new CoordinateTuple { X = 31, Y = 5},
                                                         new CoordinateTuple { X = 31, Y = 4},
                                                         new CoordinateTuple { X = 31, Y = 3},
                                                       }
                } ,

                new Route {
                    From = new Location { Position = new CoordinateTuple { X = 19, Y = 15}, MapObj = new MapObject { Type = MapObjectType.Garage, number = 2} },
                    To = new Location { Position =  new CoordinateTuple { X = 31, Y = 2}, MapObj = new MapObject { Type = MapObjectType.Runway, number = 2 } },
                    Points = new List<CoordinateTuple> { new CoordinateTuple { X = 19, Y = 14},
                                                         new CoordinateTuple { X = 19, Y = 13},
                                                         new CoordinateTuple { X = 19, Y = 12},
                                                         new CoordinateTuple { X = 20, Y = 12},
                                                         new CoordinateTuple { X = 21, Y = 12},
                                                         new CoordinateTuple { X = 22, Y = 12},
                                                         new CoordinateTuple { X = 23, Y = 12},
                                                         new CoordinateTuple { X = 24, Y = 12},
                                                         new CoordinateTuple { X = 25, Y = 12},
                                                         new CoordinateTuple { X = 26, Y = 12},
                                                         new CoordinateTuple { X = 27, Y = 12},
                                                         new CoordinateTuple { X = 28, Y = 12},
                                                         new CoordinateTuple { X = 29, Y = 12},
                                                         new CoordinateTuple { X = 30, Y = 12},
                                                         new CoordinateTuple { X = 31, Y = 12},
                                                         new CoordinateTuple { X = 31, Y = 12},
                                                         new CoordinateTuple { X = 31, Y = 12},
                                                         new CoordinateTuple { X = 31, Y = 10},
                                                         new CoordinateTuple { X = 31, Y = 9},
                                                         new CoordinateTuple { X = 31, Y = 8},
                                                         new CoordinateTuple { X = 31, Y = 7},
                                                         new CoordinateTuple { X = 31, Y = 6},
                                                         new CoordinateTuple { X = 31, Y = 5},
                                                         new CoordinateTuple { X = 31, Y = 4},
                                                         new CoordinateTuple { X = 31, Y = 3},
                                                       }
                } ,
                new Route {
                    From = new Location { Position = new CoordinateTuple { X = 4, Y = 13}, MapObj = new MapObject { Type = MapObjectType.ServiceArea, number = 1} },
                    To = new Location { Position =  new CoordinateTuple { X = 31, Y = 2}, MapObj = new MapObject { Type = MapObjectType.Runway, number = 2 } },
                    Points = new List<CoordinateTuple> { new CoordinateTuple { X = 9, Y = 12},
                                                         new CoordinateTuple { X = 9, Y = 11},
                                                         new CoordinateTuple { X = 10, Y = 11},
                                                         new CoordinateTuple { X = 11, Y = 11},
                                                         new CoordinateTuple { X = 12, Y = 11},
                                                         new CoordinateTuple { X = 13, Y = 11},
                                                         new CoordinateTuple { X = 14, Y = 11},
                                                         new CoordinateTuple { X = 15, Y = 11},
                                                         new CoordinateTuple { X = 16, Y = 11},
                                                         new CoordinateTuple { X = 17, Y = 11},
                                                         new CoordinateTuple { X = 18, Y = 11},
                                                         new CoordinateTuple { X = 19, Y = 11},
                                                         new CoordinateTuple { X = 20, Y = 11},
                                                         new CoordinateTuple { X = 21, Y = 11},
                                                         new CoordinateTuple { X = 22, Y = 11},
                                                         new CoordinateTuple { X = 23, Y = 11},
                                                         new CoordinateTuple { X = 24, Y = 11},
                                                         new CoordinateTuple { X = 25, Y = 11},
                                                         new CoordinateTuple { X = 26, Y = 11},
                                                         new CoordinateTuple { X = 27, Y = 11},
                                                         new CoordinateTuple { X = 28, Y = 11},
                                                         new CoordinateTuple { X = 29, Y = 11},
                                                         new CoordinateTuple { X = 30, Y = 11},
                                                         new CoordinateTuple { X = 31, Y = 11},
                                                         new CoordinateTuple { X = 31, Y = 10},
                                                         new CoordinateTuple { X = 31, Y = 9},
                                                         new CoordinateTuple { X = 31, Y = 8},
                                                         new CoordinateTuple { X = 31, Y = 7},
                                                         new CoordinateTuple { X = 31, Y = 6},
                                                         new CoordinateTuple { X = 31, Y = 5},
                                                         new CoordinateTuple { X = 31, Y = 4},
                                                         new CoordinateTuple { X = 31, Y = 3},
                                                       }
                } ,

                new Route {
                    From = new Location { Position = new CoordinateTuple { X = 32, Y = 13}, MapObj = new MapObject { Type = MapObjectType.Garage, number = 1} },
                    To = new Location { Position =  new CoordinateTuple { X = 4, Y = 2}, MapObj = new MapObject { Type = MapObjectType.Runway, number = 1 } },
                    Points = new List<CoordinateTuple> { new CoordinateTuple { X = 31, Y = 13},
                                                         new CoordinateTuple { X = 31, Y = 12},
                                                         new CoordinateTuple { X = 31, Y = 11},
                                                         new CoordinateTuple { X = 31, Y = 10},
                                                         new CoordinateTuple { X = 30, Y = 10},
                                                         new CoordinateTuple { X = 29, Y = 10},
                                                         new CoordinateTuple { X = 28, Y = 10},
                                                         new CoordinateTuple { X = 27, Y = 10},
                                                         new CoordinateTuple { X = 26, Y = 10},
                                                         new CoordinateTuple { X = 25, Y = 10},
                                                         new CoordinateTuple { X = 24, Y = 10},
                                                         new CoordinateTuple { X = 31, Y = 10},
                                                         new CoordinateTuple { X = 30, Y = 10},
                                                         new CoordinateTuple { X = 29, Y = 10},
                                                         new CoordinateTuple { X = 28, Y = 10},
                                                         new CoordinateTuple { X = 27, Y = 10},
                                                         new CoordinateTuple { X = 26, Y = 10},
                                                         new CoordinateTuple { X = 25, Y = 10},
                                                         new CoordinateTuple { X = 24, Y = 10},
                                                         new CoordinateTuple { X = 23, Y = 10},
                                                         new CoordinateTuple { X = 22, Y = 10},
                                                         new CoordinateTuple { X = 21, Y = 10},
                                                         new CoordinateTuple { X = 20, Y = 10},
                                                         new CoordinateTuple { X = 19, Y = 10},
                                                         new CoordinateTuple { X = 18, Y = 10},
                                                         new CoordinateTuple { X = 17, Y = 10},
                                                         new CoordinateTuple { X = 16, Y = 10},
                                                         new CoordinateTuple { X = 15, Y = 10},
                                                         new CoordinateTuple { X = 14, Y = 10},
                                                         new CoordinateTuple { X = 13, Y = 10},
                                                         new CoordinateTuple { X = 12, Y = 10},
                                                         new CoordinateTuple { X = 11, Y = 10},
                                                         new CoordinateTuple { X = 10, Y = 10},
                                                         new CoordinateTuple { X = 9, Y = 10},
                                                         new CoordinateTuple { X = 8, Y = 10},
                                                         new CoordinateTuple { X = 7, Y = 10},
                                                         new CoordinateTuple { X = 6, Y = 10},
                                                         new CoordinateTuple { X = 5, Y = 10},
                                                         new CoordinateTuple { X = 4, Y = 10},
                                                         new CoordinateTuple { X = 4, Y = 9},
                                                         new CoordinateTuple { X = 4, Y = 8},
                                                         new CoordinateTuple { X = 4, Y = 7},
                                                         new CoordinateTuple { X = 4, Y = 6},
                                                         new CoordinateTuple { X = 4, Y = 5},
                                                         new CoordinateTuple { X = 4, Y = 4},
                                                         new CoordinateTuple { X = 4, Y = 3},

                                                       }
                } ,

                new Route {
                    From = new Location { Position = new CoordinateTuple { X = 19, Y = 15}, MapObj = new MapObject { Type = MapObjectType.Garage, number = 2} },
                    To = new Location { Position =  new CoordinateTuple { X = 4, Y = 2}, MapObj = new MapObject { Type = MapObjectType.Runway, number = 1 } },
                    Points = new List<CoordinateTuple> { new CoordinateTuple { X = 18, Y = 15},
                                                         new CoordinateTuple { X = 18, Y = 14},
                                                         new CoordinateTuple { X = 18, Y = 13},
                                                         new CoordinateTuple { X = 18, Y = 12},
                                                         new CoordinateTuple { X = 18, Y = 11},
                                                         new CoordinateTuple { X = 17, Y = 11},
                                                         new CoordinateTuple { X = 16, Y = 11},
                                                         new CoordinateTuple { X = 15, Y = 11},
                                                         new CoordinateTuple { X = 14, Y = 11},
                                                         new CoordinateTuple { X = 13, Y = 11},
                                                         new CoordinateTuple { X = 12, Y = 11},
                                                         new CoordinateTuple { X = 11, Y = 11},
                                                         new CoordinateTuple { X = 10, Y = 11},
                                                         new CoordinateTuple { X = 9, Y = 11},
                                                         new CoordinateTuple { X = 8, Y = 11},
                                                         new CoordinateTuple { X = 7, Y = 11},
                                                         new CoordinateTuple { X = 6, Y = 11},
                                                         new CoordinateTuple { X = 5, Y = 11},
                                                         new CoordinateTuple { X = 4, Y = 11},
                                                         new CoordinateTuple { X = 4, Y = 10},
                                                         new CoordinateTuple { X = 4, Y = 9},
                                                         new CoordinateTuple { X = 4, Y = 8},
                                                         new CoordinateTuple { X = 4, Y = 7},
                                                         new CoordinateTuple { X = 4, Y = 6},
                                                         new CoordinateTuple { X = 4, Y = 5},
                                                         new CoordinateTuple { X = 4, Y = 4},
                                                         new CoordinateTuple { X = 4, Y = 3},

                                                       }
                } ,
                new Route {
                    From = new Location { Position = new CoordinateTuple { X = 27, Y = 16}, MapObj = new MapObject { Type = MapObjectType.Airport, number = 1} },
                    To = new Location { Position =  new CoordinateTuple { X = 4, Y = 2}, MapObj = new MapObject { Type = MapObjectType.Runway, number = 1 } },
                    Points = new List<CoordinateTuple> { new CoordinateTuple { X = 22, Y = 16},
                                                         new CoordinateTuple { X = 22, Y = 15},
                                                         new CoordinateTuple { X = 22, Y = 14},
                                                         new CoordinateTuple { X = 22, Y = 13},
                                                         new CoordinateTuple { X = 22, Y = 12},
                                                         new CoordinateTuple { X = 21, Y = 12},
                                                         new CoordinateTuple { X = 20, Y = 12},
                                                         new CoordinateTuple { X = 19, Y = 12},
                                                         new CoordinateTuple { X = 18, Y = 12},
                                                         new CoordinateTuple { X = 17, Y = 12},
                                                         new CoordinateTuple { X = 16, Y = 12},
                                                         new CoordinateTuple { X = 15, Y = 12},
                                                         new CoordinateTuple { X = 14, Y = 12},
                                                         new CoordinateTuple { X = 13, Y = 12},
                                                         new CoordinateTuple { X = 12, Y = 12},
                                                         new CoordinateTuple { X = 11, Y = 12},
                                                         new CoordinateTuple { X = 10, Y = 12},
                                                         new CoordinateTuple { X = 9, Y = 12},
                                                         new CoordinateTuple { X = 8, Y = 12},
                                                         new CoordinateTuple { X = 7, Y = 12},
                                                         new CoordinateTuple { X = 6, Y = 12},
                                                         new CoordinateTuple { X = 5, Y = 12 },
                                                         new CoordinateTuple { X = 4, Y = 12},
                                                         new CoordinateTuple { X = 4, Y = 12},
                                                         new CoordinateTuple { X = 4, Y = 12},
                                                         new CoordinateTuple { X = 4, Y = 12},
                                                         new CoordinateTuple { X = 4, Y = 12},
                                                         new CoordinateTuple { X = 4, Y = 11},
                                                         new CoordinateTuple { X = 4, Y = 10},
                                                         new CoordinateTuple { X = 4, Y = 9},
                                                         new CoordinateTuple { X = 4, Y = 8},
                                                         new CoordinateTuple { X = 4, Y = 7},
                                                         new CoordinateTuple { X = 4, Y = 6},
                                                         new CoordinateTuple { X = 4, Y = 5},
                                                         new CoordinateTuple { X = 4, Y = 4},
                                                         new CoordinateTuple { X = 4, Y = 3},

                                                       }
                } ,
                new Route {
                    From = new Location { Position = new CoordinateTuple { X = 4, Y = 13}, MapObj = new MapObject { Type = MapObjectType.ServiceArea, number = 1} },
                    To = new Location { Position = new CoordinateTuple { X = 19, Y = 15}, MapObj = new MapObject { Type = MapObjectType.Garage, number = 2} },
                    Points = new List<CoordinateTuple> { new CoordinateTuple { X = 10, Y = 15},
                                                         new CoordinateTuple { X = 11, Y = 15},
                                                         new CoordinateTuple { X = 12, Y = 15},
                                                         new CoordinateTuple { X = 13, Y = 15},
                                                         
                                                       }
                } ,
                new Route {
                    From = new Location { Position = new CoordinateTuple { X = 4, Y = 13}, MapObj = new MapObject { Type = MapObjectType.ServiceArea, number = 1} },
                    To = new Location { Position = new CoordinateTuple { X = 27, Y = 16}, MapObj = new MapObject { Type = MapObjectType.Airport, number = 1} },
                    Points = new List<CoordinateTuple> { new CoordinateTuple { X = 10, Y = 14},
                                                         new CoordinateTuple { X = 11, Y = 14},
                                                         new CoordinateTuple { X = 12, Y = 14},
                                                         new CoordinateTuple { X = 13, Y = 14},
                                                         new CoordinateTuple { X = 14, Y = 14},
                                                         new CoordinateTuple { X = 15, Y = 14},
                                                         new CoordinateTuple { X = 16, Y = 14},
                                                         new CoordinateTuple { X = 17, Y = 14},
                                                         new CoordinateTuple { X = 18, Y = 14},
                                                         new CoordinateTuple { X = 19, Y = 14},
                                                         new CoordinateTuple { X = 20, Y = 14},
                                                         new CoordinateTuple { X = 21, Y = 14},
                                                         new CoordinateTuple { X = 22, Y = 14},
                                                         new CoordinateTuple { X = 23, Y = 14},
                                                         new CoordinateTuple { X = 23, Y = 15},

                                                       }
                } ,
                new Route {
                    From = new Location { Position = new CoordinateTuple { X = 4, Y = 13}, MapObj = new MapObject { Type = MapObjectType.ServiceArea, number = 1} },
                    To = new Location { Position = new CoordinateTuple { X = 32, Y = 13}, MapObj = new MapObject { Type = MapObjectType.Garage, number = 1} },
                    Points = new List<CoordinateTuple> { new CoordinateTuple { X = 10, Y = 13},
                                                         new CoordinateTuple { X = 11, Y = 13},
                                                         new CoordinateTuple { X = 12, Y = 13},
                                                         new CoordinateTuple { X = 13, Y = 13},
                                                         new CoordinateTuple { X = 14, Y = 13},
                                                         new CoordinateTuple { X = 15, Y = 13},
                                                         new CoordinateTuple { X = 16, Y = 13},
                                                         new CoordinateTuple { X = 17, Y = 13},
                                                         new CoordinateTuple { X = 18, Y = 13},
                                                         new CoordinateTuple { X = 19, Y = 13},
                                                         new CoordinateTuple { X = 20, Y = 13},
                                                         new CoordinateTuple { X = 21, Y = 13},
                                                         new CoordinateTuple { X = 22, Y = 13},
                                                         new CoordinateTuple { X = 23, Y = 13},
                                                         new CoordinateTuple { X = 24, Y = 13},
                                                         new CoordinateTuple { X = 25, Y = 13},
                                                         new CoordinateTuple { X = 26, Y = 13},
                                                         new CoordinateTuple { X = 27, Y = 13},
                                                         new CoordinateTuple { X = 28, Y = 13},
                                                         new CoordinateTuple { X = 29, Y = 13},
                                                         new CoordinateTuple { X = 30, Y = 13},
                                                         new CoordinateTuple { X = 31, Y = 13},
                                                         


                                                       }
                } ,



            };
        }
    }
}